### ISSUE TITLE
Creating Nuxt.js website fails because of is-promise 

### ISSUE THREAD

**Issue by NicolasMaas** [then/is-promise#22]
Hi everyone

Bear with me, this is the first time I open up an issue as a junior developer. I'm trying to create a Nuxt.js website but when I try to create it, it fails and your module has something to do with it. 

Are you guys aware of the issue or not? Not entirely sure if this is the way to address this issue since it's Nuxt.js related but I think this module is causing the failure.

Sorry if this has been submitted in the wrong place. Then just delete it but maybe this will get me more answers 😅

**Comment by preetjdp** [comment]
Hey @NicolasMaas this issue has been resolved.
Re Running the npx command should fix everything.

More details on the fix here https://github.com/then/is-promise/issues/20

**Comment by NicolasMaas** [comment]
I've updated my global packages and reran the npx command but it still fails.
